import { Modal, Button } from 'react-bootstrap';

interface Props {
  show: boolean;
  /**
   * Index of the earliest earlier pair that is now incomplete (because new
   * shadow annotations were generated by the matches the user just made). If
   * undefined, nothing earlier needs attention.
   */
  earlierIncompleteIndex?: number;
  /** Called when the user accepts the suggestion shown. */
  onConfirm: () => void;
  /** Called if the user wants to stay on the current pair. */
  onStay: () => void;
}

/**
 * Shown by the harness once the user has accepted every candidate on the
 * current pair. Two flavours:
 *
 *   1. earlierIncompleteIndex defined → "an earlier pair needs your
 *      attention. Go back?" (because confirming a match here may have caused
 *      Munkres to invent new shadows on a pair you'd previously finished).
 *   2. else → "no earlier pair needs work. Move on to the next pair?"
 *
 * The harness drives both branches; this component is purely presentational.
 */
export function PairCompleteDialog({
  show,
  earlierIncompleteIndex,
  onConfirm,
  onStay,
}: Props) {
  const goBack = earlierIncompleteIndex !== undefined;
  return (
    <Modal show={show} onHide={onStay} centered>
      <Modal.Header closeButton>
        <Modal.Title>Pair complete</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        {goBack ? (
          <>
            All annotations on this pair are now linked. New shadow markers
            have appeared on pair{' '}
            <strong>{(earlierIncompleteIndex as number) + 1}</strong>, which
            you have already worked on. Would you like to go back and resolve
            it now?
          </>
        ) : (
          <>
            All annotations on this pair are now linked, and no earlier pair
            needs attention. Move on to the next pair?
          </>
        )}
      </Modal.Body>
      <Modal.Footer>
        <Button variant='secondary' onClick={onStay}>
          Stay here
        </Button>
        <Button variant='primary' onClick={onConfirm}>
          {goBack ? 'Go back' : 'Next pair'}
        </Button>
      </Modal.Footer>
    </Modal>
  );
}
